name: md
channels:
  - r
  - anaconda
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=ha9d2b57_10
  - bandage=0.8.1=hb59a952_0
  - bbmap=38.90=he522d1c_1
  - blas=1.0=mkl
  - blast=2.9.0=pl526he19e7b1_5
  - boost=1.71.0=py36_0
  - boost-cpp=1.71.0=h7b6447c_0
  - bowtie2=2.3.5.1=py36he513fc3_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2020.10.14=0
  - cairo=1.14.12=h8948797_3
  - cd-hit=4.8.1=hdbcaa40_0
  - cd-hit-auxtools=4.6.8=hc9558a2_2
  - certifi=2020.6.20=py36_0
  - circos=0.69.6=4
  - curl=7.75.0=h979ede3_0
  - cycler=0.10.0=py36_0
  - datamash=1.1.0=0
  - dbus=1.13.12=h746ee38_0
  - diamond=0.9.21=1
  - entrez-direct=13.9=pl526h375a9b1_0
  - expat=2.2.9=he6710b0_2
  - fastqc=0.11.8=0
  - fontconfig=2.13.0=h9420a91_0
  - freebayes=1.3.2=py36ha64edc8_2
  - freetype=2.10.2=h5ab3b9f_0
  - fribidi=1.0.10=h7b6447c_0
  - gettext=0.19.8.1=h9b4dc7a_1
  - giflib=5.1.4=h14c3975_1
  - glib=2.56.2=hd408876_0
  - glimmerhmm=3.0.4=pl526hf484d3e_3
  - gmp=6.1.2=hb3b607b_0
  - gnutls=3.6.5=h71b1129_1002
  - graphite2=1.3.14=h23475e2_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - htslib=1.12=hd3b49d5_0
  - icu=58.2=he6710b0_3
  - intel-openmp=2020.2=254
  - joblib=0.13.2=py36_0
  - jpeg=9b=habf39ab_1
  - kernel-headers_linux-64=3.10.0=h77966d4_10
  - kiwisolver=1.2.0=py36hfd86e86_0
  - krb5=1.17.1=h173b8e3_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libboost=1.71.0=h97c9712_0
  - libcurl=7.75.0=hc4aaa36_0
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20181209=hc058e9b_0
  - libev=4.33=h7b6447c_0
  - libffi=3.3=he6710b0_2
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgd=2.2.5=h0db58fd_3
  - libgfortran-ng=8.2.0=hdf63c60_1
  - libgomp=9.3.0=h2828fa1_18
  - libiconv=1.15=h63c8f33_5
  - libnghttp2=1.43.0=h812cca2_0
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libwebp=1.0.1=h8e7db2f_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=he19cac6_1
  - llvm-openmp=8.0.1=hc9558a2_0
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py36h817c723_0
  - miniasm=0.3_r179=hed695b0_1
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.2.0=py36h23d657b_0
  - mkl_random=1.0.4=py36hd81dba3_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.4.1=hbb512f6_0
  - numpy=1.19.1=py36hbc911f0_0
  - numpy-base=1.19.1=py36hfa32c7d_0
  - nxtrim=0.4.3=h9a82719_1
  - olefile=0.46=py36_0
  - openjdk=11.0.1=h516909a_1016
  - openmp=8.0.1=0
  - openssl=1.1.1j=h7f98852_0
  - pango=1.42.4=h049681c_0
  - parallel=20210222=ha770c72_0
  - pbzip2=1.1.13=0
  - pcre=8.44=he6710b0_0
  - perl=5.26.2=h14c3975_0
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-archive-tar=2.32=pl526_0
  - perl-autoloader=5.74=pl526_2
  - perl-base=2.23=pl526_1
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-clone=0.42=pl526h516909a_0
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.087=pl526he1b5a44_0
  - perl-compress-raw-zlib=2.087=pl526hc9558a2_0
  - perl-config-general=2.63=pl526_0
  - perl-constant=1.33=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-digest-hmac=1.03=pl526_3
  - perl-digest-md5=2.55=pl526_0
  - perl-digest-perl-md5=1.9=pl526_1
  - perl-dynaloader=1.25=pl526_1
  - perl-encode=2.88=pl526_1
  - perl-encode-locale=1.05=pl526_6
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-file-listing=6.04=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-temp=0.2304=pl526_2
  - perl-font-ttf=1.06=pl526_0
  - perl-gd=2.71=pl526he860b03_0
  - perl-html-parser=3.72=pl526h6bb024c_5
  - perl-html-tagset=3.20=pl526_3
  - perl-html-tree=5.07=pl526_1
  - perl-http-cookies=6.04=pl526_0
  - perl-http-daemon=6.01=pl526_1
  - perl-http-date=6.02=pl526_3
  - perl-http-message=6.18=pl526_0
  - perl-http-negotiate=6.01=pl526_3
  - perl-io-compress=2.087=pl526he1b5a44_0
  - perl-io-html=1.001=pl526_2
  - perl-io-socket-ssl=2.066=pl526_0
  - perl-io-string=1.08=pl526_3
  - perl-io-zlib=1.10=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-libwww-perl=6.36=pl526_1
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-lwp-mediatypes=6.04=pl526_0
  - perl-lwp-protocol-https=6.07=pl526_4
  - perl-math-bezier=0.01=pl526_1
  - perl-math-round=0.07=pl526_1
  - perl-math-vecstat=0.08=pl526_1
  - perl-mime-base64=3.15=pl526_1
  - perl-module-implementation=0.09=pl526_2
  - perl-module-runtime=0.016=pl526_1
  - perl-mozilla-ca=20180117=pl526_1
  - perl-net-http=6.18=pl526_0
  - perl-net-ssleay=1.88=pl526h90d6eec_0
  - perl-ntlm=1.09=pl526_4
  - perl-number-format=1.75=pl526_3
  - perl-params-validate=1.29=pl526h14c3975_1
  - perl-parent=0.236=pl526_1
  - perl-pathtools=3.75=pl526h14c3975_1
  - perl-readonly=2.05=pl526_0
  - perl-regexp-common=2017060201=pl526_0
  - perl-scalar-list-utils=1.52=pl526h516909a_0
  - perl-set-intspan=1.19=pl526_1
  - perl-socket=2.027=pl526_1
  - perl-statistics-basic=1.6611=pl526_2
  - perl-storable=3.15=pl526h14c3975_0
  - perl-svg=2.84=pl526_0
  - perl-test-requiresinternet=0.05=pl526_0
  - perl-text-format=0.59=pl526_2
  - perl-time-hires=1.9760=pl526h14c3975_1
  - perl-time-local=1.28=pl526_1
  - perl-try-tiny=0.30=pl526_1
  - perl-types-serialiser=1.0=pl526_2
  - perl-uri=1.76=pl526_0
  - perl-www-robotrules=6.02=pl526_3
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-parser=2.44=pl526h4e0c4b3_7
  - perl-xml-sax=1.00=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xml-sax-expat=0.51=pl526_3
  - perl-xml-simple=2.25=pl526_1
  - perl-xsloader=0.24=pl526_0
  - pillow=7.2.0=py36hb39fc2d_0
  - pilon=1.22=py36_0
  - pip=20.2.2=py36_0
  - pixman=0.40.0=h7b6447c_0
  - py-boost=1.71.0=py36h0573a6f_0
  - pyparsing=2.3.1=py36_0
  - pyqt=5.9.2=py36h05f1152_2
  - python=3.6.10=h0371630_0
  - python-dateutil=2.8.0=py36_0
  - python_abi=3.6=1_cp36m
  - qt=5.9.7=h5867ecd_1
  - quast=5.0.2=py36pl526ha92aebf_0
  - racon=1.4.20=he513fc3_0
  - readline=7.0=h7b6447c_5
  - samtools=1.12=h9aed4be_1
  - seqtk=1.3=hed695b0_2
  - setuptools=49.6.0=py36_0
  - simplejson=3.17.2=py36h7b6447c_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.14.0=py36_0
  - spades=3.15.2=h95f258a_1
  - sqlite=3.31.1=h7b6447c_0
  - sysroot_linux-64=2.17=h77966d4_10
  - tbb=2020.3=hfd86e86_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.0.4=py36h7b6447c_1
  - unicycler=0.4.8=py36hd181a71_3
  - wheel=0.34.2=py36_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
